### ISSUE TITLE
Build failure in toysolver-0.5.0 with GHC 9.2

### ISSUE THREAD

**Issue by sjakobi** [msakai/toysolver#75]
```
src/SAT.hs:2:28: warning:
    -XDoRec is deprecated: use -XRecursiveDo or pragma {-# LANGUAGE RecursiveDo #-} instead
  |
2 | {-# LANGUAGE BangPatterns, DoRec, ScopedTypeVariables, CPP, DeriveDataTypeable #-}
  |                            ^^^^^
[ 1 of 79] Compiling Algebra.Lattice.Boolean ( src/Algebra/Lattice/Boolean.hs, dist/build/Algebra/Lattice/Boolean.o, dist/build/Algebra/Lattice/Boolean.dyn_o )

src/Algebra/Lattice/Boolean.hs:54:10: error:
    • Variable not in scope: meet :: a -> a -> a
    • Perhaps you meant one of these:
        data constructor ‘Meet’ (imported from Algebra.Lattice),
        ‘meets’ (imported from Algebra.Lattice)
   |
54 | (.&&.) = meet
   |          ^^^^

src/Algebra/Lattice/Boolean.hs:58:10: error:
    • Variable not in scope: join :: a -> a -> a
    • Perhaps you meant one of these:
        data constructor ‘Join’ (imported from Algebra.Lattice),
        ‘joins’ (imported from Algebra.Lattice)
   |
58 | (.||.) = join
   |          ^^^^
cabal: Failed to build toysolver-0.0.5
```

**Comment by sjakobi** [comment]
FYI, I don't think that such an old version ought to be compatible with GHC-9.2. But it would be good to add some constraints, so `cabal` won't try to build it with recent versions of GHC. Alternatively, old versions with build failures could simply be deprecated.

**Comment by msakai** [comment]
Thanks for the report.
The problem seems to be the missing upper bound of `lattice` package.
I'll revise the package metadata on Hackage to add such upper bound when I have time.

**Comment by sjakobi** [comment]
It seems that the bound on `lattices` should be `< 2`. As a Hackage trustee, I've added this bound to v0.0.5 and v0.0.6:

* https://hackage.haskell.org/package/toysolver-0.0.5/revisions/
* https://hackage.haskell.org/package/toysolver-0.0.6/revisions/

Unfortunately, there are more build failures remaining. For example, I get this with GHC 7.10.3:

```
src/Data/IndexedPriorityQueue.hs:85:7: error:
    • Non type-variable argument
        in the constraint: A.MArray A.IOUArray Index m
      (Use FlexibleContexts to permit this)
    • When checking the inferred type
        go :: forall (m :: * -> *).
              A.MArray A.IOUArray Index m =>
              Value -> m ()
      In the expression:
        do (_, arr) <- readIORef (heap q)
           writeIORef (heap q) (0, arr)
           idx <- readIORef (table q)
           (!lb, !ub) <- A.getBounds idx
           ....
      In an equation for ‘clear’:
          clear q
            = do (_, arr) <- readIORef (heap q)
                 writeIORef (heap q) (0, arr)
                 idx <- readIORef (table q)
                 ....
   |
85 |   let go i
   |       ^^^^...

src/Data/IndexedPriorityQueue.hs:154:7: error:
    • Non type-variable argument
        in the constraint: Dequeue PriorityQueue m Value
      (Use FlexibleContexts to permit this)
    • When checking the inferred type
        go :: forall (m :: * -> *).
              Dequeue PriorityQueue m Value =>
              [Value] -> m [Value]
      In an equation for ‘dequeueBatch’:
          dequeueBatch q
            = go []
            where
                go xs
                  = do r <- dequeue q
                       ....
      In the instance declaration for ‘Dequeue PriorityQueue IO Value’
    |
154 |       go xs = do
    |       ^^^^^^^^^^...
cabal: Failed to build toysolver-0.0.5
```

**Comment by sjakobi** [comment]
I have also created revisions for some of the other versions and managed to remove some broken build plans. Some still remain though. See https://matrix.hackage.haskell.org/#/package/toysolver.

**Comment by sjakobi** [comment]
I've corrected all the bad build plans reported in https://matrix.hackage.haskell.org/#/package/toysolver for now.

Note that I've had to add a bound `base < 4.15` to the latest v0.7.0: https://hackage.haskell.org/package/toysolver-0.7.0/revisions/

You may want to apply the same bound in `master` or alternatively fix the build with GHC 9.0 and 9.2.
